import crafttweaker.item.IItemStack;

// ########################################################
// If you truly disagree with my disabling of an item from
// the modpack, find and delete its entry in this list.
// ########################################################

val disabledItemsList = [
	<cgm:workbench>,
	<quarryplus:replacer_module>,
	<rustic:apiary>,
	<grapplemod:staffupgradeitem>,
	<grapplemod:launcheritem>,
	<grapplemod:repeller>,
	<grapplemod:forcefieldupgradeitem>,
	<enderio:item_dark_steel_helmet>,
	<enderio:item_dark_steel_chestplate>,
	<enderio:item_dark_steel_leggings>,
	<enderio:item_dark_steel_boots>,
	<enderio:item_end_steel_helmet>,
	<enderio:item_end_steel_chestplate>,
	<enderio:item_end_steel_leggings>,
	<enderio:item_end_steel_boots>,
	<survivalism:mixing_spoon>,
	<survivalism:mixing_vat>,
	<survivalism:crushing_vat>,
	<survivalism:compost>,
	<survivalism:compost_bin>,
	<survivalism:barrel_brewing>,
	<survivalism:drying_rack>,
	<bullseye:arrow:9>,
	<bullseye:arrow:4>,
	<notenoughwands:wandcore>,
	<notenoughwands:advanced_wandcore>,
	<notenoughwands:swapping_wand>,
	<notenoughwands:teleportation_wand>,
	<notenoughwands:potion_wand>,
	<notenoughwands:freezing_wand>,
	<notenoughwands:master_protection_wand>,
	<notenoughwands:protection_wand>,
	<notenoughwands:acceleration_wand>,
	<notenoughwands:capturing_wand>,
	<potionfingers:ring>,
	<enderio:block_reservoir>,
	<vending:vendingmachineadvanced:*>,
	<vending:vendingstorageattachment>,
	<advancedrocketry:arcfurnace>,
	<foundry:alloyfurnace>,
	<libvulpes:coalgenerator>,
	<enderio:block_enhanced_alloy_smelter>,
	<immersiveengineering:metal_device1:13>,
	<enderio:block_transceiver>,
	<enderio:block_simple_sag_mill>,
	<enderio:block_sag_mill>,
	<enderio:block_enhanced_sag_mill>,
	<enderio:block_simple_alloy_smelter>,
	<enderio:block_alloy_smelter>,
	<modularutilities:ender_proxy>,
	<foundry:machine:3>,
	<advancedrocketry:platepress>,
	<quarryplus:workbenchplus>,
	<quarryplus:quarryreplacer>,
	<quarryplus:solidquarry>,
	<quarryplus:standalonepump>,
	<quarryplus:spawnercontroller>,
	<quarryplus:breakerplus>,
	<quarryplus:placerplus>,
	<immersiveengineering:metal_device1:3>,
	<cyclicmagic:gold_furnace_minecart>,
	<cyclicmagic:turret_minecart>,
	<cyclicmagic:dropper_minecart>,
	<cyclicmagic:stone_minecart>,
	<cyclicmagic:gold_minecart>,
	<itemfilters:filter>,
	<rustic:bee>,
	<rustic:beehive>,
	<rustic:honeycomb>,
	<enderio:item_material:6>,
	<enderio:item_material:7>,
	<enderio:item_material:69>,
	<enderio:item_material:68>,
	
	<forestry:miner_bag>,
	<forestry:miner_bag_t2>,
	<forestry:digger_bag>,
	<forestry:digger_bag_t2>,
	<forestry:forester_bag>,
	<forestry:forester_bag_t2>,
	<forestry:hunter_bag>,
	<forestry:hunter_bag_t2>,
	<forestry:adventurer_bag>,
	<forestry:adventurer_bag_t2>,
	<forestry:builder_bag>,
	<forestry:builder_bag_t2>,
	<railcraft:backpack_iceman_t1>,
	<railcraft:backpack_iceman_t2>,
	<railcraft:backpack_trackman_t1>,
	<railcraft:backpack_trackman_t2>,
	<railcraft:backpack_signalman_t1>,
	<railcraft:backpack_signalman_t2>,
	
	<familiarfauna:pixie_dust>,
	<familiarfauna:snail_shell>,
	
	<railcraft:detector:3>,
	<railcraft:detector:5>,
	<defiledlands:concussion_smasher>,
	<grapplemod:enderhook>.withTag({doublehook: 0 as byte, motor: 0 as byte, phaserope: 0 as byte, attract: 0 as byte, rocket: 0 as byte, hookgravity: 1.0, repelforce: 1.0, attractradius: 3.0, pullbackwards: 1 as byte, smartmotor: 0 as byte, detachonkeyrelease: 0 as byte, angle: 20.0, rocket_vertical_angle: 0.0, rocket_force: 1.0, rocket_refuel_ratio: 15.0, motorwhencrouching: 0 as byte, motorwhennotcrouching: 1 as byte, motordampener: 0 as byte, rocket_active_time: 0.5, throwspeed: 3.5, motoracceleration: 0.2, enderstaff: 1 as byte, oneropepull: 0 as byte, sneakingverticalthrowangle: 0.0, smartdoublemotor: 1 as byte, repel: 0 as byte, sneakingangle: 10.0, motormaxspeed: 4.0, playermovementmult: 1.0, reelin: 1 as byte, sticky: 0 as byte, verticalthrowangle: 0.0, maxlen: 60.0}),
	<grapplemod:magnethook>.withTag({doublehook: 0 as byte, motor: 0 as byte, phaserope: 0 as byte, attract: 1 as byte, rocket: 0 as byte, hookgravity: 1.0, repelforce: 1.0, attractradius: 3.0, pullbackwards: 1 as byte, smartmotor: 0 as byte, detachonkeyrelease: 0 as byte, angle: 20.0, rocket_vertical_angle: 0.0, rocket_force: 1.0, rocket_refuel_ratio: 15.0, motorwhencrouching: 0 as byte, motorwhennotcrouching: 1 as byte, motordampener: 0 as byte, rocket_active_time: 0.5, throwspeed: 3.5, motoracceleration: 0.2, enderstaff: 0 as byte, oneropepull: 0 as byte, sneakingverticalthrowangle: 0.0, smartdoublemotor: 1 as byte, repel: 1 as byte, sneakingangle: 10.0, motormaxspeed: 4.0, playermovementmult: 1.0, reelin: 1 as byte, sticky: 0 as byte, verticalthrowangle: 0.0, maxlen: 60.0}),
	
	<icbmclassic:explosives:29>,
	<icbmclassic:explosives:30>,
	<icbmclassic:missile:28>,
	<icbmclassic:missile:27>,
	<icbmclassic:missile:30>,
	<icbmclassic:missile:29>,
	<icbmclassic:missile:25>,
	<icbmclassic:explosives:12>,
	<icbmclassic:explosives:16>,
	<icbmclassic:missile:12>,
	<icbmclassic:batterybox>,
	<icbmclassic:bombcart:12>,
	<icbmclassic:explosives:14>,
	<icbmclassic:grenade:29>,
	<icbmclassic:grenade:30>,
	<buildinggadgets:destructiontool>,
	<advancedrocketry:microwavereciever>,
	<funkylocomotion:teleporter>,
	
	] as IItemStack[];

for disabledItems in disabledItemsList {
	disabledItems.addTooltip(format.red("ITEM DISABLED BY MODPACK DEV."));
	disabledItems.addTooltip(format.lightPurple("IMBALANCE, REDUNDANCY, TASTE."));
	disabledItems.addTooltip(format.yellow("SURELY THERE WAS A GOOD REASON."));
	mods.jei.JEI.removeAndHide(disabledItems);
	}
	
mods.jei.JEI.hideCategory("SagMill");
mods.jei.JEI.hideCategory("foundry.alloyfurnace");
mods.jei.JEI.hideCategory("foundry.infuser");
mods.jei.JEI.hideCategory("quarryplus.workbenchplus");

val vanishedItemsList = [

<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:apiarist_armor_chest"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:apiarist_armor_chest", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:apiarist_armor_feet"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:apiarist_armor_feet", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:apiarist_armor_head"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:apiarist_armor_head", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:apiarist_armor_legs"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:apiarist_armor_legs", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:elytra"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:elytra", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:glide"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:glide", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv1"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv1", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv2"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:inv2", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:jumpboost1"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:jumpboost1", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:jumpboost2"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:jumpboost2", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:jumpboost3"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:jumpboost3", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:naturalist_eye"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiointegrationforestry:naturalist_eye", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:nightvision"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:nightvision", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:padding"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:padding", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiomachines:solar"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiomachines:solar", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiomachines:solar1"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiomachines:solar1", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiomachines:solar2"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiomachines:solar2", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiomachines:solar3"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderiomachines:solar3", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:sounddetector"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:sounddetector", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:speedboost1"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:speedboost1", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:speedboost2"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:speedboost2", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:speedboost3"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:speedboost3", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:step_assist"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:step_assist", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:swim"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:swim", "enderio:enabled": 1 as byte}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:top"}),
<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:top", "enderio:enabled": 1 as byte}),

] as IItemStack[];

for vanishedItem in vanishedItemsList {
	mods.jei.JEI.removeAndHide(vanishedItem);
	vanishedItem.addTooltip(format.red("This item is irrelevant with darksteel and endsteel armor disabled."));
	}
